---
title: "Lab 3 Report"
output: html_document
---

## Background

The General Social Survey (GSS) has been run by NORC every other year since 1972 to keep track of current opinions across the United States. 


Variable - Description :
------------------------
Year - year of response (1972-2016, every other year)
Age - age of respondent
Sex - sex of respondent (Male or Female)
marital - Marital status of respondent (Divorced, Married, Never Married, Separated, Widowed)
degree - highest level of education for respondent (Bachelor, Graduate, High school, Junior Collge, Lt High School)
health - Health of the respondent (on a Poor to Excellent scale)
partyid - the political affiliation of the respondent (on a scale from Strong Democrat to Strong Republican)


## The Data Cleaning Process



The different types of missing values (IAP, DK, NA) were replace with 'NA'. This was done by the following code:

'''{r}
happy <- readRDS("C:/Users/wogie/OneDrive/DS202/HAPPY.rds")
names(happy) = tolower(names(happy))

happy$polviews[happy$polviews %in% "IAP"] <- "NA"
happy$polviews[happy$polviews %in% "DK"] <- "NA"
happy$health[happy$health %in% "IAP"] <- "NA"
happy$health[happy$health %in% "DK"] <- "NA"
happy$finrela[happy$finrela %in% "IAP"] <- "NA"
happy$finrela[happy$finrela %in% "DK"] <- "NA"

'''
The following code is how I cast Variables into the correct type to make the data visualization process more straightforward.

'''{r}
happy$age[happy$age == '89 OR OLDER'] <- "89"
happy$happy = as.character(happy$happy)
happy$year = as.numeric(happy$year)
happy$age = as.numeric(happy$age)
happy$sex = as.character(happy$sex)
happy$marital = as.character(happy$marital)
happy$degree = as.character(happy$degree)
happy$finrela = as.character(happy$finrela)
happy$health = as.character(happy$health)
happy$wtssall = as.numeric(happy$wtssall)
happy$partyid = as.character(happy$partyid)
happy$polviews = as.character(happy$polviews)
'''

I decided that ordering all of the Factors according to age would make sense because it is a relevant characteristic for all other Factors.

'''{r}
library(tidyverse)

happyVSage = fct_reorder(happy$happy, happy$age, .fun=median, .desc = FALSE)
sexVSage = fct_reorder(happy$sex, happy$age, .fun=median, .desc = FALSE)
maritalVSage = fct_reorder(happy$marital, happy$age, .fun=median, .desc = FALSE)
degreeVSage = fct_reorder(happy$degree, happy$age, .fun=median, .desc = FALSE)
finrelaVSage = fct_reorder(happy$finrela, happy$age, .fun=median, .desc = FALSE)
healthVSage = fct_reorder(happy$health, happy$age, .fun=median, .desc = FALSE)
partyidVSage = fct_reorder(happy$partyid, happy$age, .fun=median, .desc = FALSE)
polviewsVSage = fct_reorder(happy$polviews, happy$age, .fun=median, .desc = FALSE)
'''


## Data Exploration

For the data exploration, I used 4 different types of 'geoms': Histogram, Boxplot, Frequency Polygon, and Bar Chart. I used different types of geoms because they are most useful for exploring data in different ways. 

Two interesting variables in this set are Sex and Degree. The distributions of both are shown below in relation to another variable, Age. 

'''{r}
library(ggplot2)
ggplot(happy, aes(year, fill = sex)) + geom_histogram(binwidth=2) + labs(title="Histogram of Age by Sex", x="Year", y="Count")

'''

'''{r}
ggplot(happy, aes(degree, age)) + geom_boxplot() + labs(title = "Boxplot of Degree by Age")

'''


This Visualization shows a fairly strong relationship between Health and Happiness. While the Percentage of reports of "Pretty Happy" Seem fairly unwavering across levels of health, There are clearly more reports of "Not Too Happy" in the "Poor" Health category and many more reports of "Very Happy" in the "Excellent" Health category.
'''{r}
ggplot(happy, aes(health, fill=happy)) + geom_bar(color="red", position="fill") + coord_flip() + labs(title = "Barchart of Health as it relates to Happiness", x="Health", y="Percentage")
'''

According to this visualization, which is a frequency polygon showing the effect of age on happiness.  Reports of "Pretty Happy" were definitely higher from the 20-50 age bracket than the 50-75 age bracket. The two ends of the spectrum "Not Too Happy" and "Very Happy" varied less than the middle category as age progressed. 
'''{r}
ggplot(happy, aes(age, color=happy)) + geom_freqpoly(binwidth=1) + labs(title = "Comparison of Happiness and Age", x="Age", y="Count")
'''

This is a barchart displaying the effect of marital status on happiness in the dataset. The most striking piece of information gathered from this comparison is the noticaeably low percentage of married people who reported "Not too Happy."
'''{r}
ggplot(happy, aes(marital, fill=happy)) + geom_bar(position="fill") + labs(title="Barchart of Happiness and Marital Status", y="percentage", x="Level of Happiness")
'''
 
 I learned a lot of valuable things from this data exploration excercise. I not only strengthed and practiced my skills at data cleaning, exploration, and analysis/explanation. I also learned that, according to the dataset and my choices for visualizations, the "Happiest" Person is someone who is in Excellent Health, between the age of 25-40, and married. 
 This conclusion seems like a reasonable one considering my own personal experience and observation of the natural world around me. Those that are in good health will be happier because mood is effected by how the body is doing physically. I have heard many places that the happiest people are married people so this also makes sense. 